export const FETCH_COLORS_DATA_REQUEST = 'FETCH_COLORS_DATA_REQUEST';
export const FETCH_COLORS_DATA_SUCCESS = 'FETCH_COLORS_DATA_SUCCESS';
export const FETCH_COLORS_DATA_FAIL = 'FETCH_COLORS_DATA_FAIL';
