export const FETCH_COLORS_DATA_REQUEST = 'FETCH_COLORS_DATA_REQUEST';
export const FETCH_COLORS_DATA_SUCCESS = 'FETCH_COLORS_DATA_SUCCESS';
export const FETCH_COLORS_DATA_FAIL = 'FETCH_COLORS_DATA_FAIL';
export const SELECT_BACKGROUND_COLOR = 'SELECT_BACKGROUND_COLOR';
export const SELECT_TEXT_COLOR = 'SELECT_TEXT_COLOR';
export const SELECT_BUTTON_COLOR = 'SELECT_BUTTON_COLOR';
export const SELECT_BUTTON_TEXT_COLOR = 'SELECT_BUTTON_TEXT_COLOR';
